version: "3"

services:
  nodejs:
    build:
      dockerfile: Dockerfile
    ports:
      - 8077:8076
    depends_on: 
     - mongodb
    env_file: 
      development.env
  mongodb:
    image: mongo:4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 27018:27017
    volumes:
      - .dbmongodb:/var/lib/lib/mongodb
